// AUTOGENERATED by amboras-dev-orchestrator (Phase C — multi-theme A/B).
// CONTRACT v6
// Do NOT edit by hand. Source of truth:
//   backend/src/modules/plugins/templates/middleware-template.ts
//
// This file is shipped to every storefront unconditionally. The
// AB_ENABLED env-var check on the first line of middleware() short-circuits
// flag-off stores at zero cost beyond one boolean read per request.
//
// Cookies set here (amb_vid, amb_fp, amb_theme) are strictly-necessary
// under GDPR/ePrivacy: they exist solely to deliver the variant the buyer
// has been assigned to — no profiling, no cross-site tracking. They are
// intentionally NOT routed through lib/cookie-consent.ts (review item L6).
//
// amboras_consent (geo auto-consent, CONTRACT v6) is different: it IS the
// consent record owned client-side by lib/cookie-consent.ts. The middleware
// writes it — analytics:true — ONLY for visitors outside the ePrivacy
// opt-in jurisdictions (EEA + UK + CH) and ONLY when no decision cookie
// exists yet, so relaxed-cookie-law traffic gets analytics from the first
// page view without a banner. Opt-in-country and unknown-geo visitors are
// never auto-granted (banner shows as before); an explicit Decline is
// never overridden.

import { NextRequest, NextResponse } from 'next/server'

const AB_ENABLED = process.env.AB_ENABLED === 'true'
const ROUTER_URL = process.env.VARIANT_ROUTER_URL
const ROUTER_SECRET = process.env.VARIANT_ROUTER_SECRET
// orchestrator stores.id (uuid). NOT the same as NEXT_PUBLIC_STORE_ID, which
// is the dev-env uuid used as the Medusa tenant key. The variant-router keys
// snapshots by stores.id — passing the Medusa tenant key here returns
// reason=no_group for every resolve and the AB never fires. See template
// header comment for the full why.
const STORE_ID = process.env.NEXT_PUBLIC_AB_STORE_ID
// Staging-only escape hatch: when 'true', `?_v=<slug>` is honored without
// the admin-cookie check. Wired here as a deferred mechanism for
// review item C3 (full admin-JWT verification ships when the orchestrator
// learns to mint `amb_admin` from the dashboard "Preview" action).
const PREVIEW_OVERRIDE_ENABLED = process.env.PREVIEW_OVERRIDE_ENABLED === 'true'

export const config = {
  matcher: [
    // Match every path except framework internals, the public API surface,
    // and obvious static assets — but DO include the JS chunk + CSS asset
    // paths so middleware can rewrite them to the variant deploy on AB
    // stores (post-2026-05-30 middleware-proxy architecture). Fonts /
    // images / media are still excluded to keep middleware invocation
    // volume bounded (review item perf-2: ~30 chunks/css per page load is
    // OK; ~hundreds of font/image requests is not).
    '/_next/static/chunks/:path*',
    '/_next/static/css/:path*',
    '/((?!_next/|api/|favicon\\.ico|robots\\.txt|sitemap\\.xml).*)',
  ],
}

const BOT_UA_RE = /bot|crawl|spider|slurp|googlebot|bingbot|baidu|yandex|duckduckbot|facebookexternalhit|twitterbot|linkedinbot/i

// Device classification — MUST mirror the variant-router's targeting.ts so a
// device switch is detected the same way the router applies device targeting
// (tablet before mobile; iPads sometimes carry "Mobile" in the UA). Used only to
// invalidate the cookie fast path when the device changes within the TTL window,
// so device-targeted assignments (and same-browser responsive testing) stay live.
const TABLET_UA_RE = /ipad|tablet|playbook|kindle|silk(?!.*mobile)/i
const MOBILE_UA_RE = /mobi|iphone|ipod|android(?!.*tablet)|blackberry|opera mini|windows phone/i
function classifyDevice(ua: string): 'mobile' | 'tablet' | 'desktop' {
  if (!ua) return 'desktop'
  if (TABLET_UA_RE.test(ua)) return 'tablet'
  if (MOBILE_UA_RE.test(ua)) return 'mobile'
  return 'desktop'
}

const COOKIE_OPTS = {
  sameSite: 'lax' as const,
  secure: true,
  path: '/',
}
const THIRTY_DAYS = 60 * 60 * 24 * 30
const NINETY_DAYS = 60 * 60 * 24 * 90
// How long a signed assignment is trusted before the middleware re-resolves
// through the router. Within this window a returning visitor is served straight
// from the cookie (no router/Redis round-trip), which is the dominant page-view
// cost. Admin changes (targeting/weight/promote/cancel/rebuild) reach an active
// visitor on their next re-resolve, i.e. within this TTL; new visitors and
// anyone past it get them immediately. In milliseconds (compared vs Date.now()).
const RESOLVE_TTL_MS = 5 * 60 * 1000

// ── Geo auto-consent (CONTRACT v6) ──────────────────────────────────────────
// Countries with ePrivacy-style OPT-IN cookie law keep the consent banner;
// everyone else gets analytics consent auto-granted server-side so analytics
// (v2 ingest, PostHog, Meta pixel — all gated on hasAnalyticsConsent()) are
// live from the first page view. List = EU27 + EEA (IS/LI/NO) + UK + CH.
// Unknown/missing country (e.g. local dev, non-Vercel edge) → keep banner.
const CONSENT_OPT_IN_COUNTRIES = new Set([
  'AT','BE','BG','HR','CY','CZ','DK','EE','FI','FR','DE','GR','HU','IE','IT',
  'LV','LT','LU','MT','NL','PL','PT','RO','SK','SI','ES','SE',
  'IS','LI','NO','GB','CH',
])
// Contract owned by lib/cookie-consent.ts: URL-encoded JSON {analytics, ts},
// absence = undecided (banner shows). Names/values MUST stay in sync with it.
const CONSENT_COOKIE = 'amboras_consent'
const CONSENT_MAX_AGE = 31536000 // 1 year — mirrors client-side CONSENT_MAX_AGE

// Auto-grant analytics consent for visitors outside the opt-in jurisdictions.
// Never overrides an existing decision cookie (an explicit Decline stays).
// The extra `auto: 'geo'` field is additive — hasAnalyticsConsent() only
// checks `analytics === true` — and marks the grant as geo-derived rather
// than an explicit Accept click. NextResponse.cookies.set URL-encodes the
// JSON value, matching the client's decodeURIComponent + JSON.parse.
function applyGeoConsent(req: NextRequest, response: NextResponse): NextResponse {
  if (req.cookies.get(CONSENT_COOKIE)?.value) return response
  const country = (req.headers.get('x-vercel-ip-country') ?? '').toUpperCase()
  if (!country || CONSENT_OPT_IN_COUNTRIES.has(country)) return response
  response.cookies.set(
    CONSENT_COOKIE,
    JSON.stringify({ analytics: true, ts: new Date().toISOString(), auto: 'geo' }),
    { ...COOKIE_OPTS, maxAge: CONSENT_MAX_AGE },
  )
  return response
}

interface ResolveResponse {
  themeId: string
  deploymentUrl: string
  isControl: boolean
  fingerprint?: string
  groupVersion: string
  // The active A/B group id (null on control fallbacks). Carried into the
  // amb_theme cookie so the ab-attribution plugin can stamp ab_group_id onto
  // analytics events. Without it every event lands NULL and the A/B rollup
  // (which filters on ab_group_id IS NOT NULL) shows zero.
  abGroupId?: string | null
  assignedAt?: string
  reason?: string
}

interface CookiePayload {
  themeId: string
  groupVersion: string
  // Optional + additive: pre-2026-05-31 cookies omit it. The ab-attribution
  // plugin reads it from the decoded cookie payload; verify() does not require
  // it so old signed cookies remain valid.
  abGroupId?: string | null
  // Epoch ms when this assignment was last resolved through the router. The HTML
  // path trusts the cookie (skips the router) while `Date.now() - resolvedAt <
  // RESOLVE_TTL_MS`. Optional + additive: pre-v4 cookies omit it and are treated
  // as expired (re-resolve once), so the rollout is seamless.
  resolvedAt?: number
  // Device class (classifyDevice) at the time of resolve. The fast path only
  // trusts the cookie while the current request's device matches — a device
  // switch (responsive testing, or device-targeted experiments) re-resolves so
  // device targeting stays live. Optional + additive: pre-v5 cookies omit it and
  // therefore re-resolve once.
  device?: string
  // The variant deploy URL for this assignment, as returned by the router's
  // /v1/resolve (`resolved.deploymentUrl`). Empty/absent ⇒ control.
  //
  // Carried in the cookie ONLY because the asset-proxy branch
  // (/_next/static/*) must rewrite ~30 chunk/CSS requests per page WITHOUT a
  // router round-trip each. It is safe to trust as a rewrite target because
  // the whole payload is HMAC-signed (signCookie/verifyCookie) — a forged URL
  // can't pass verification (this satisfies the original C1 concern, which was
  // about UNSIGNED cookie data dictating the rewrite). The HTML path does NOT
  // read this; it uses the fresh `resolved.deploymentUrl` from its own resolve
  // call. Edge Config (the previous URL source) was removed: it duplicated the
  // router snapshot and its per-store 3-config cap blocked new stores.
  deploymentUrl?: string | null
}

// Edge entrypoint. The function is declared as `middleware` here because that
// is the Next 15 convention. When the orchestrator ships this file to a Next
// 16+ store, `renderEdgeTemplate(PROXY_CONVENTION_PATH)` rewrites the
// declaration to `export async function proxy(` — Next 16 requires the entry
// function to be named `proxy` (or default), not just the file. This mirrors
// the official @next/codemod middleware-to-proxy, which renames both file and
// function together.
export async function proxy(req: NextRequest) {
  // ── H1: short-circuit on flag-off stores. MUST be the first line. ──────────
  if (!AB_ENABLED || !ROUTER_URL || !ROUTER_SECRET || !STORE_ID) {
    // Diagnostic-friendly short-circuit: expose which env piece is missing so
    // the publish-time multi-theme env-var self-heal can be debugged from a
    // simple `curl -I`. No PII, no secrets — just yes/no flags for the
    // canonical env vars. Cheap (one boolean per env on flag-off stores).
    const response = NextResponse.next()
    response.headers.set(
      'x-amb-short-circuit',
      [
        AB_ENABLED ? 'AB_ENABLED' : '!AB_ENABLED',
        ROUTER_URL ? 'ROUTER_URL' : '!ROUTER_URL',
        ROUTER_SECRET ? 'ROUTER_SECRET' : '!ROUTER_SECRET',
        STORE_ID ? 'STORE_ID' : '!STORE_ID',
      ].join(','),
    )
    // Mint the per-visitor id even when theme A/B is OFF. `amb_vid` is the
    // sticky visitor key that the PRODUCT-page (PDP) A/B feature needs — that
    // feature is server-side in Medusa and runs independently of the theme
    // router, so its visitor cookie must not be gated behind the theme-A/B
    // flags above. The Medusa backend decides per request whether any PDP
    // experiment is actually running; the storefront's only job is to always
    // carry a stable visitor id. Strictly-necessary, no profiling (random UUID).
    if (!req.cookies.get('amb_vid')?.value) {
      response.cookies.set('amb_vid', crypto.randomUUID(), {
        ...COOKIE_OPTS,
        maxAge: THIRTY_DAYS,
      })
    }
    return applyGeoConsent(req, response)
  }

  // ── Bots: serve control deterministically. Strip ?_v so crawlers cannot
  //    fragment indexing by following a leaked preview URL (review item C3).
  const ua = req.headers.get('user-agent') ?? ''
  if (BOT_UA_RE.test(ua)) {
    if (req.nextUrl.searchParams.has('_v')) {
      const stripped = new URL(req.nextUrl.toString())
      stripped.searchParams.delete('_v')
      return NextResponse.redirect(stripped)
    }
    return NextResponse.next()
  }

  // ── Asset proxy branch ─────────────────────────────────────────────────────
  // Requests for /_next/static/chunks/* and /_next/static/css/* must be
  // routed to the SAME deploy that produced the HTML referencing them, or
  // the buyer gets cross-deploy chunk skew (different content hashes between
  // control and variant builds). The cookie tells us which deploy that is.
  //
  // No cookie ⇒ this is either a cold visit (HTML response will set the
  // cookie) or a control buyer ⇒ either way serve control assets. Bad
  // cookie ⇒ also serve control (defense in depth, no PII).
  const isAssetRequest = req.nextUrl.pathname.startsWith('/_next/static/')
  if (isAssetRequest) {
    const cookieRaw = req.cookies.get('amb_theme')?.value
    if (!cookieRaw) return NextResponse.next()
    const verified = await verifyCookie(cookieRaw, ROUTER_SECRET)
    if (!verified) return NextResponse.next()
    // The signed cookie carries the variant deploy URL (empty ⇒ control).
    // Trusted because the payload is HMAC-verified above. No router/Edge Config
    // call on the asset hot path.
    const variantUrl = verified.deploymentUrl
    if (!variantUrl) return NextResponse.next()
    try {
      const rewriteUrl = new URL(
        req.nextUrl.pathname + req.nextUrl.search,
        variantUrl,
      )
      return NextResponse.rewrite(rewriteUrl)
    } catch {
      return NextResponse.next()
    }
  }

  // ── ?_v=<slug> preview override (review item C3) ───────────────────────────
  // Requires either:
  //   1. an admin auth cookie set by the orchestrator dashboard, OR
  //   2. PREVIEW_OVERRIDE_ENABLED=true (staging escape hatch)
  // Without one of these the param is silently ignored — it never leaks
  // variants to anonymous traffic. Note: the cookie's existence is checked
  // but not cryptographically verified at this layer; the orchestrator
  // dashboard issues it short-TTL + scoped to the storefront origin.
  const previewSlug = req.nextUrl.searchParams.get('_v')
  if (previewSlug) {
    const isAdmin = !!req.cookies.get('amb_admin')?.value
    if (isAdmin || PREVIEW_OVERRIDE_ENABLED) {
      const resolved = await callRouter(req, ua, { previewSlug })
      if (resolved) {
        return finalize(req, resolved)
      }
      // Router error on explicit preview → fall through to normal flow
      // rather than 5xx the admin.
    }
  }

  // ── Cookie fast path ───────────────────────────────────────────────────────
  // Cookie payload is base64url(JSON({themeId, groupVersion})).base64url(hmac).
  // We do NOT trust a deploymentUrl from the cookie (review item C1).
  const cookieRaw = req.cookies.get('amb_theme')?.value
  if (cookieRaw) {
    const verified = await verifyCookie(cookieRaw, ROUTER_SECRET)
    if (verified) {
      // Fast path: within RESOLVE_TTL_MS AND while the device is unchanged, trust
      // the signed cookie and skip the router entirely — no cross-region
      // router+Redis round-trip on this page view. The assignment stays sticky
      // (correct for a running experiment). The HTML rewrite target is the
      // cookie's signed deploymentUrl (same value the asset branch already trusts).
      // The device check keeps device-targeted assignments live across a device
      // switch (e.g. responsive testing) — a changed device re-resolves below.
      const age =
        typeof verified.resolvedAt === 'number' ? Date.now() - verified.resolvedAt : Infinity
      const sameDevice = verified.device === classifyDevice(ua)
      if (age >= 0 && age < RESOLVE_TTL_MS && sameDevice) {
        return finalize(
          req,
          {
            themeId: verified.themeId,
            groupVersion: verified.groupVersion,
            abGroupId: verified.abGroupId ?? null,
            deploymentUrl: verified.deploymentUrl ?? '',
            isControl: !verified.deploymentUrl,
          },
          { skipThemeCookieWrite: true }, // preserve resolvedAt → honour the TTL window
        )
      }
      // TTL expired (or a pre-v4 cookie with no resolvedAt) → re-resolve through
      // the router to pick up any lifecycle / targeting / weight / rebuild change,
      // then refresh the cookie (resets resolvedAt, starting a new TTL window).
      const resolved = await callRouter(req, ua, {
        ambFp: req.cookies.get('amb_fp')?.value,
      })
      if (!resolved) return applyGeoConsent(req, NextResponse.next()) // router down → control
      return finalize(req, resolved)
    }
    // Cookie present but signature/structure invalid → treat as miss.
  }

  // ── Cookie miss: call FastAPI /v1/resolve ──────────────────────────────────
  const resolved = await callRouter(req, ua, {
    ambFp: req.cookies.get('amb_fp')?.value,
  })
  if (!resolved) return applyGeoConsent(req, NextResponse.next()) // router unreachable → serve control
  return finalize(req, resolved)
}

// ─── helpers ────────────────────────────────────────────────────────────────

interface CallRouterExtras {
  ambFp?: string
  previewSlug?: string
}

async function callRouter(
  req: NextRequest,
  ua: string,
  extras: CallRouterExtras,
): Promise<ResolveResponse | null> {
  try {
    const res = await fetch(`${ROUTER_URL}/v1/resolve`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'x-router-secret': ROUTER_SECRET ?? '',
      },
      body: JSON.stringify({
        storeId: STORE_ID,
        ip: req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ?? '',
        country: req.headers.get('x-vercel-ip-country') ?? '',
        region: req.headers.get('x-vercel-ip-country-region') ?? '',
        language: req.headers.get('accept-language') ?? '',
        timezone: req.headers.get('x-vercel-ip-timezone') ?? '',
        userAgent: ua,
        utmSource: req.nextUrl.searchParams.get('utm_source') ?? undefined,
        ambFp: extras.ambFp,
        ambVid: req.cookies.get('amb_vid')?.value,
        previewSlug: extras.previewSlug,
      }),
    })
    if (!res.ok) return null
    return (await res.json()) as ResolveResponse
  } catch {
    return null
  }
}

interface FinalizeOptions {
  /** When the router confirmed the same (themeId, groupVersion) as the
   *  cookie already carries, skip rewriting the amb_theme cookie.
   *  The cookie's max-age does not roll forward — that's intentional;
   *  the buyer's experience stays pinned to the original assignment
   *  until the snapshot rotates. */
  skipThemeCookieWrite?: boolean
}

async function finalize(
  req: NextRequest,
  resolved: ResolveResponse,
  opts: FinalizeOptions = {},
): Promise<NextResponse> {
  let response: NextResponse
  if (resolved.isControl) {
    response = NextResponse.next()
  } else {
    // Variant deploy URL comes straight from the router's resolve response.
    // The router snapshot is refreshed by the orchestrator on every A/B
    // lifecycle event (launch / weight / targeting / enable / promote /
    // cancel) from the same DB rows that used to feed Edge Config, so it is
    // the single source of truth for "where is the current variant served?".
    const variantUrl = resolved.deploymentUrl
    if (!variantUrl) {
      // No URL yet (snapshot mid-build / propagation lag) — fall back to
      // control. Buyer sees the same control HTML uncookied visitors see; no
      // broken state.
      response = NextResponse.next()
    } else {
      let rewriteUrl: URL
      try {
        rewriteUrl = new URL(
          req.nextUrl.pathname + req.nextUrl.search,
          variantUrl,
        )
      } catch {
        return applyGeoConsent(req, NextResponse.next())
      }
      response = NextResponse.rewrite(rewriteUrl)
    }
  }

  if (!opts.skipThemeCookieWrite && ROUTER_SECRET) {
    const signed = await signCookie(
      {
        themeId: resolved.themeId,
        groupVersion: resolved.groupVersion,
        abGroupId: resolved.abGroupId ?? null,
        // Stamp the resolve time so the HTML fast path can trust this cookie for
        // RESOLVE_TTL_MS before re-resolving. Always written on a fresh resolve,
        // which resets the TTL window.
        resolvedAt: Date.now(),
        // Stamp the device this assignment was resolved for; the fast path
        // re-resolves if the request's device later differs (keeps device
        // targeting live across a device switch).
        device: classifyDevice(req.headers.get('user-agent') || ''),
        // Persist the (signed) variant URL so the asset-proxy branch can
        // rewrite /_next/static/* without a router call. Empty for control.
        deploymentUrl: resolved.isControl ? '' : (resolved.deploymentUrl ?? ''),
      },
      ROUTER_SECRET,
    )
    response.cookies.set('amb_theme', signed, { ...COOKIE_OPTS, maxAge: THIRTY_DAYS })
  }
  if (resolved.fingerprint) {
    response.cookies.set('amb_fp', resolved.fingerprint, {
      ...COOKIE_OPTS,
      maxAge: NINETY_DAYS,
    })
  }
  if (!req.cookies.get('amb_vid')?.value) {
    response.cookies.set('amb_vid', crypto.randomUUID(), {
      ...COOKIE_OPTS,
      maxAge: THIRTY_DAYS,
    })
  }
  return applyGeoConsent(req, response)
}

// HMAC cookie sign/verify using Web Crypto (works at Vercel edge).
// Format: `<base64url(JSON)>.<base64url(hmac_sha256(secret, base64url(JSON)))>`

async function signCookie(payload: CookiePayload, secret: string): Promise<string> {
  const json = JSON.stringify(payload)
  const data = b64urlEncode(new TextEncoder().encode(json))
  const sig = await hmacSign(data, secret)
  return `${data}.${sig}`
}

async function verifyCookie(
  cookie: string,
  secret: string,
): Promise<CookiePayload | null> {
  const dot = cookie.indexOf('.')
  if (dot <= 0 || dot === cookie.length - 1) return null
  const data = cookie.slice(0, dot)
  const sig = cookie.slice(dot + 1)
  const expected = await hmacSign(data, secret)
  // Constant-time compare (review item C1 hardening).
  if (!timingSafeEqual(sig, expected)) return null
  let parsed: unknown
  try {
    parsed = JSON.parse(new TextDecoder().decode(b64urlDecode(data)))
  } catch {
    return null
  }
  if (
    !parsed ||
    typeof parsed !== 'object' ||
    typeof (parsed as CookiePayload).themeId !== 'string' ||
    typeof (parsed as CookiePayload).groupVersion !== 'string'
  ) {
    return null
  }
  return parsed as CookiePayload
}

async function hmacSign(data: string, secret: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  )
  const sigBuf = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(data))
  return b64urlEncode(new Uint8Array(sigBuf))
}

function b64urlEncode(bytes: Uint8Array): string {
  let bin = ''
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i])
  return btoa(bin).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

function b64urlDecode(s: string): Uint8Array {
  const pad = s.length % 4 === 0 ? '' : '='.repeat(4 - (s.length % 4))
  const b64 = s.replace(/-/g, '+').replace(/_/g, '/') + pad
  const bin = atob(b64)
  const out = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i)
  return out
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false
  let diff = 0
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i)
  return diff === 0
}
